import type { Metadata } from "next";
import "./globals.scss";
import { Providers } from "@/shared/components/shared/providers";

// !TODO: remove this metadata to another layout
export const metadata: Metadata = {
  title: "NUWM Diploma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
